/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class ViewReportsWindow extends javax.swing.JFrame {

    public ViewReportsWindow() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        byAmount = new javax.swing.JButton();
        allOrders = new javax.swing.JButton();
        byQty = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        viewCustomers = new javax.swing.JButton();
        bestInCustomers = new javax.swing.JButton();
        allCustomers = new javax.swing.JButton();
        ordersByAmount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports");
        setResizable(false);

        byAmount.setBackground(new java.awt.Color(51, 0, 204));
        byAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        byAmount.setForeground(new java.awt.Color(255, 255, 255));
        byAmount.setText("Categorized By Amount");
        byAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byAmountActionPerformed(evt);
            }
        });

        allOrders.setBackground(new java.awt.Color(0, 153, 153));
        allOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        allOrders.setForeground(new java.awt.Color(255, 255, 255));
        allOrders.setText("All Orders");
        allOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allOrdersActionPerformed(evt);
            }
        });

        byQty.setBackground(new java.awt.Color(51, 0, 204));
        byQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        byQty.setForeground(new java.awt.Color(255, 255, 255));
        byQty.setText("Categorized By QTY");
        byQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byQtyActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(205, 113, 63));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        viewCustomers.setBackground(new java.awt.Color(102, 255, 0));
        viewCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewCustomers.setForeground(new java.awt.Color(255, 255, 255));
        viewCustomers.setText("View Customers");
        viewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersActionPerformed(evt);
            }
        });

        bestInCustomers.setBackground(new java.awt.Color(102, 255, 0));
        bestInCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bestInCustomers.setForeground(new java.awt.Color(255, 255, 255));
        bestInCustomers.setText("Best In Customers");
        bestInCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestInCustomersActionPerformed(evt);
            }
        });

        allCustomers.setBackground(new java.awt.Color(102, 255, 0));
        allCustomers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        allCustomers.setForeground(new java.awt.Color(255, 255, 255));
        allCustomers.setText("All Customers");
        allCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCustomersActionPerformed(evt);
            }
        });

        ordersByAmount.setBackground(new java.awt.Color(0, 153, 153));
        ordersByAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordersByAmount.setForeground(new java.awt.Color(255, 255, 255));
        ordersByAmount.setText("Orders By Amount");
        ordersByAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersByAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bestInCustomers)
                    .addComponent(viewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(byQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(byAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ordersByAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(bestInCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(allCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ordersByAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(allOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(byQty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(byAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        Main.f1.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersActionPerformed

        new ViewCustomersWindow().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_viewCustomersActionPerformed

    private void allCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCustomersActionPerformed
        new AllCustomersWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_allCustomersActionPerformed

    private void ordersByAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersByAmountActionPerformed
        new OrdersByAmountWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ordersByAmountActionPerformed

    private void bestInCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestInCustomersActionPerformed
        new BestInCustomersWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bestInCustomersActionPerformed

    private void byQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byQtyActionPerformed
        new CategorizedByQtyWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_byQtyActionPerformed

    private void byAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byAmountActionPerformed
        new CategorizedByAmountWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_byAmountActionPerformed

    private void allOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allOrdersActionPerformed
       new AllOrdersWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_allOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReportsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReportsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allCustomers;
    private javax.swing.JButton allOrders;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bestInCustomers;
    private javax.swing.JButton byAmount;
    private javax.swing.JButton byQty;
    private javax.swing.JButton ordersByAmount;
    private javax.swing.JButton viewCustomers;
    // End of variables declaration//GEN-END:variables
}
